# Generated by Django 4.1.3 on 2022-11-30 12:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('slots', models.ManyToManyField(to='home.slot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
