# Generated by Django 4.1.3 on 2022-12-12 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_counselloruser_clientuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_client', to='home.clientuser'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='counsellor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_counsellor', to='home.counselloruser'),
        ),
        migrations.AlterField(
            model_name='freeslot',
            name='counsellor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.counselloruser'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='counsellor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.counselloruser'),
        ),
        migrations.AlterField(
            model_name='servicepack',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_pack_client', to='home.clientuser'),
        ),
        migrations.AlterField(
            model_name='servicepack',
            name='counsellor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_pack_counsellor', to='home.counselloruser'),
        ),
    ]
